---
os: linux
arch: arm64-graviton2
dist: bionic
language: python
python:
  - 3.8
sudo: required
services:
  - docker

jobs:
  include:
    - stage: build-test
      install:
        - pip install --upgrade pip
        - make venv
      script:
        - set -e
        - make build-all
        - venv/bin/pytest -v

stages:
  - name: build-test
    if: branch = main
